FROM golang:1.6.2

# build gobase image for harbor/ui and harbor/job
# $ docker build -f Dockerfile.gobase -t gobase:latest .
MAINTAINER scorpiocph@gmail.com

RUN apt-get update \
    && apt-get install -y libldap2-dev \
    && rm -r /var/lib/apt/lists/* \
    && go get -d github.com/docker/distribution \
    && go get -d github.com/docker/libtrust \
    && go get -d github.com/go-sql-driver/mysql
