# build ubuntu base image with docker
# $ docker build -f Dockerfile_ubuntu_base -t ubuntu_base:latest .

FROM ubuntu:16.04

MAINTAINER scorpiocph@gmail.com

# install docker
RUN apt-get update \
    && apt-get install docker.io -y

# install python
RUN apt-get install build-essential checkinstall -y \
    && apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev -y \
    && cd ~/ \
    && apt-get install wget -y \
    && wget http://python.org/ftp/python/2.7.12/Python-2.7.12.tgz \
    && tar -xvf Python-2.7.12.tgz \
    && cd Python-2.7.12 \
    && ./configure \
    && make install
